# Generated by Django 6.0.3 on 2026-03-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта при получении'), ('payme', 'PayMe'), ('click', 'Click')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
